server:
   max-http-header-size: 10000
jdb:
  orm:
    default-jdb-orm-conf: jdb-orm.conf.xml
    data-source-close-method-name: close
    enable-redis-store-mapping: true
    
spring:
  redis:
    host: localhost
    database: 0
    port: 6379
   
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=douglei
    username: sa
    password: 123123
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
i18n:
  enable-redis-store: true

